# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Navigator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QToolBar

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 748)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnBack.setObjectName("btnBack")
        self.gridLayout.addWidget(self.btnBack, 0, 0, 1, 1)
        self.btnForWard = QtWidgets.QPushButton(self.centralwidget)
        self.btnForWard.setObjectName("btnForWard")
        self.gridLayout.addWidget(self.btnForWard, 0, 1, 1, 1)
        self.btnHome = QtWidgets.QPushButton(self.centralwidget)
        self.btnHome.setObjectName("btnHome")
        self.gridLayout.addWidget(self.btnHome, 0, 2, 1, 1)
        self.btnRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.gridLayout.addWidget(self.btnRefresh, 0, 3, 1, 1)
        #this is line to manage navbar
        self.btnAddTab = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddTab.setIconSize(QtCore.QSize(16, 16))
        self.btnAddTab.setObjectName("btnAddTab")
        self.gridLayout.addWidget(self.btnAddTab, 0, 5, 1, 1)
        self.tabNavigator = QtWidgets.QTabWidget(self.centralwidget)
        self.tabNavigator.setObjectName("tabNavigator")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabNavigator.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabNavigator, 1, 0, 1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1055, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabNavigator.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnBack.setText(_translate("MainWindow", "⏪"))
        self.btnForWard.setText(_translate("MainWindow", "⏩"))
        self.btnHome.setText(_translate("MainWindow", "🏠"))
        self.btnRefresh.setText(_translate("MainWindow", "🌀"))
        self.btnAddTab.setText(_translate("MainWindow", "➕"))
        self.tabNavigator.setTabText(self.tabNavigator.indexOf(self.tab), _translate("MainWindow", "Tab"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
